better readme ig
MinusMCNetwork/MinusBounce pull request #11
Opened 2023-11-22 12:07 UTC by Rylazius

tui bili:

2023-11-22 14:00 UTC, toidicakhia requested changes

2023-11-22 14:00 UTC, toidicakhia commented on README.md
> +A free forge hacked-client for Minecraft supporting version 1.8.9, built for HeroMC
no build for heromc
"build for bypassing multiserver"

2023-11-23 05:13 UTC, Rylazius commented
tui update la "with state-of-the-art bypasses"

2023-11-23 05:34 UTC, toidicakhia approved these changes

2023-11-23 05:34 UTC, merged